from playwright.sync_api import sync_playwright
import os
import time
import argparse
import sys

# Configuration
USER_DATA_DIR = os.path.expanduser("~/.instagram_browser_profile")

def post_to_instagram(image_path, caption):
    """
    Automates Instagram posting using a persistent browser context.
    """
    if not os.path.exists(image_path):
        print(f"Error: Image not found at {image_path}")
        return

    with sync_playwright() as p:
        # Launch persistent context to save login session
        print(f"Launching Browser (Profile: {USER_DATA_DIR})...")
        try:
            browser = p.chromium.launch_persistent_context(
                user_data_dir=USER_DATA_DIR,
                headless=False, # Must be False for visibility
                channel="chrome", # Try to use real Chrome
                args=["--start-maximized"]
            )
        except Exception as e:
            print(f"Error launching Chrome: {e}")
            print("Falling back to bundled Chromium...")
            browser = p.chromium.launch_persistent_context(
                user_data_dir=USER_DATA_DIR,
                headless=False
            )

        page = browser.new_page()
        page.goto("https://www.instagram.com/")
        
        # 1. Check Login
        print("Checking login status...")
        try:
            # Look for 'Create' icon (New post)
            page.wait_for_selector('svg[aria-label="New post"]', timeout=5000)
            print("Logged in!")
        except:
            print("Not logged in. Please log in manually in the browser window.")
            print("Waiting 60s for you to log in...")
            try:
                page.wait_for_selector('svg[aria-label="New post"]', timeout=60000)
                print("Login detected!")
            except:
                print("Login timed out. Exiting.")
                browser.close()
                return

        # 2. Start Creation
        print("Clicking Create...")
        page.click('svg[aria-label="New post"]')
        time.sleep(2)
        
        # 3. Handle File Upload
        print(f"Uploading {image_path}...")
        try:
            with page.expect_file_chooser() as fc_info:
                page.get_by_role("button", name="Select from computer").click()
            file_chooser = fc_info.value
            file_chooser.set_files(image_path)
        except Exception as e:
            print(f"Upload failed: {e}")
            return
            
        time.sleep(2)
        
        # 4. Filter Next (Crop/Filter steps)
        print("Processing Crop/Filter...")
        try:
            # First Next (Crop)
            page.get_by_role("button", name="Next").click()
            time.sleep(2)
            # Second Next (Filter)
            page.get_by_role("button", name="Next").click()
            time.sleep(2)
        except:
            print("Error finding Next buttons. Flow might have changed.")

        # 5. Caption
        print("Adding Caption...")
        try:
            # Locate caption area
            page.get_by_role("textbox", name="Write a caption...").fill(caption)
            time.sleep(1)
        except:
            print("Could not find caption box.")
        
        # 6. Share
        print("Sharing...")
        try:
            page.get_by_role("button", name="Share").click()
            
            # 7. Confirm Success
            page.wait_for_selector('div:has-text("Your post has been shared")', timeout=30000)
            print("SUCCESS: Post Shared!")
        except Exception as e:
            print(f"Share failed or timed out: {e}")
            
        time.sleep(5)
        browser.close()

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Auto-post to Instagram via Playwright")
    parser.add_argument("--image", required=True, help="Path to image file")
    parser.add_argument("--caption", default="Generated by POD AI #design", help="Caption text")
    
    args = parser.parse_args()
    post_to_instagram(args.image, args.caption)
